name: RunParsersTest

on:
  workflow_dispatch:
    inputs:
      cmdParams:
        description: 'cmd parameters'
        required: true
        default: '-parser markas'
        type: string

jobs:
  generateXMLFeeds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run parsers & update xml feeds
      run: |
        python updateFeeds.py -meta -feed -json -index ${{ cmdParams }}
    - name: Test files in github pages
      run: |
        python tests/test_ghpages.py
