name: RunParsers

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - 'luxembourg/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - 'luxembourg/**'
  schedule:
    - cron: "12 6 * * *" # UTC
jobs:
  generateXMLFeeds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: git config
      run: |
        git config --global user.name github-actions
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        git pull --ff-only
    - name: Run parsers & update xml feeds
      run: |
        python updateFeeds.py -meta -feed -json -index
    - name: git commit & push
      if: always()
      run: |
        git add docs
        # Use "|| true" or "--allow-empty"  otherwise the action fails for empty commits
        git commit -m "Updated xml feeds" || true
        git push
    - name: Test files in github pages
      if: always()
      run: |
        python tests/test_ghpages.py
